basicexpressframework:
  image: vincentlinsanity/basicexpressframework:latest
  links:
    - "mongo:mongo"
    - "redis:redis"
  ports:
    - "3000:3000"
    - "443:443"
mongo:
  image: mongodb:3.0.7
  expose:
    - 27017
  volumes:
    - '/home/docker/compose/meta/data/mongo:/data/db'
